spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/agri?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    # username: root
    # password: root
    url: jdbc:mysql://rm-gc78nt8lf868p2611xo.mysql.cn-chengdu.rds.aliyuncs.com:3306/agrimarket?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Fiammetta!1
    druid:
      validation-query: SELECT 1 FROM DUAL
      initial-size: 10 #初始化时建立物理连接的个数。
      min-idle: 10  #最小连接池数量
      max-active: 200 #最大连接池数量
      min-evictable-idle-time-millis: 300000 #连接保持空闲而不被驱逐的最小时间
      test-on-borrow: false  #申请连接时执行validationQuery检测连接是否有效
      test-while-idle: true #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，
      #执行validationQuery检测连接是否有效。
      time-between-eviction-runs-millis: 30000 #1) Destroy线程会检测连接的间隔时间，
      #如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      #2) testWhileIdle的判断依据
      pool-prepared-statements: true  #是否缓存preparedStatement，也就是PSCache
      max-open-prepared-statements: 100 #要启用PSCache，必须配置大于0，当大于0时，
      #poolPreparedStatements自动触发修改为true
  application:
    name: AgriBigData
    aop:
      proxy-target-class: true
  mail:
    host: smtp.163.com
    username: agriBigData@163.com
    password: FFPGJQIQZOLLYQVK

server:
  port: 8080
  servlet:
    context-path: /api


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.agri.agribigdata.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    root: INFO
    com.agri: WARN
    com.testabc.demo.ssmtest: debug
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{35} - %msg%n"
  file:
    name: ./log/logfile.log

  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 7